### 0)
POST http://localhost:8081/user/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### 1) Регистрация (получаем токен)
POST http://localhost:8080/user/auth/register
Content-Type: application/json

{
  "username": "user1",
  "password": "pass"
}

### 2) Рекомендации номеров (вставь токен вместо <TOKEN>)
GET http://localhost:8080/api/rooms/recommend?start=2025-10-26&end=2025-10-28
Authorization: dev-UNSAFE-default-change-me-1234567890

### 3) Создать бронирование (идемпотентный requestId)
POST http://localhost:8080/booking
Authorization: dev-UNSAFE-default-change-me-1234567890
Content-Type: application/json

{
  "roomId": 1,
  "startDate": "2025-10-26",
  "endDate": "2025-10-28",
  "autoSelect": false,
  "requestId": "req-42"
}

### 4) Повтор с тем же requestId (дубля не будет)
POST http://localhost:8080/booking
Authorization: dev-UNSAFE-default-change-me-1234567890
Content-Type: application/json

{
  "roomId": 1,
  "startDate": "2025-10-26",
  "endDate": "2025-10-28",
  "autoSelect": false,
  "requestId": "req-42"
}

### 5) Мои бронирования
GET http://localhost:8080/bookings
Authorization: dev-UNSAFE-default-change-me-1234567890
